/**
 * Geteilte Label-Tabellen und Selbstverraeter-Guard-Mengen fuer die generische
 * Konzept-Darstellung.
 *
 * Frueher lagen diese Konstanten privat in `ConceptVisual.jsx`. Ausgelagert, damit
 * sie an mehreren Stellen als EINE Quelle der Wahrheit dienen:
 *   - `ConceptVisual.jsx` (linkes Quiz-Panel)
 *   - Dashboard-Kategorie-Aufschluesselung (deutsche statt roher Keys)
 *   - QA-Werkzeuge (`scripts/qa_review/*`), die exakt nachbilden, WAS der Spieler
 *     vor dem Antworten sieht (Guard-Logik muss deckungsgleich sein).
 *
 * Wichtig: Diese Datei ist bewusst framework-frei (kein React-Import), damit sie
 * auch von Node-Skripten (`import`) genutzt werden kann.
 */

// Deutsche Labels fuer bekannte Kategorien (Fallback: Roh-Schluessel).
export const CATEGORY_LABELS = {
  planet: 'Planet',
  dwarf_planet: 'Zwergplanet',
  moon: 'Mond',
  star: 'Stern',
  galaxy: 'Galaxie',
  constant: 'Konstante',
  constellation: 'Sternbild',
  mission: 'Raumfahrtmission',
  bone: 'Knochen',
  muscle: 'Muskel',
  organ: 'Organ',
  body_fact: 'Körperwert',
  species: 'Menschenart',
  // Homo — Physiologie jenseits der Anatomie (Stand 2026-06-25)
  cell_type: 'Zelltyp',
  hormone: 'Hormon',
  vitamin: 'Vitamin',
  sense: 'Sinn',
  digestive_enzyme: 'Verdauungsenzym',
  nerve: 'Nerv',
  psych_effect: 'Psychoeffekt',
  nutrient_macro: 'Nährstoff',
  development_stage: 'Entwicklungsstadium',
  brain_lobe: 'Großhirnlappen',
  sleep_perception: 'Schlaf & Gedächtnis',
  // Homo — Welle 5 (Stand 2026-07-01): Gelenke, Reflexe, Blutgruppen
  joint: 'Gelenk',
  reflex: 'Reflex',
  blood_group: 'Blutgruppe',
  // Homo — Welle 6 (Stand 2026-09-02): Gefäße, Bandapparat, Gehirn, Botenstoffe,
  // Sinnesorgan-Bestandteile, Zähne, Gewebe, Immunsystem
  blood_vessel: 'Blutgefäß',
  ligament_tendon: 'Band und Sehne',
  brain_structure: 'Hirnstruktur',
  neurotransmitter: 'Botenstoff',
  sense_organ_part: 'Sinnesorgan-Teil',
  tooth: 'Zahn',
  tissue_type: 'Gewebeart',
  immune_component: 'Immunsystem',
  // Natura
  animal: 'Tier',
  plant: 'Pflanze',
  fungus: 'Pilz',
  biome: 'Lebensraum',
  geology: 'Geologie',
  mineral: 'Mineral',
  atmosphere: 'Atmosphäre',
  phenomenon: 'Naturphänomen',
  // Lingua
  language: 'Sprache',
  language_family: 'Sprachfamilie',
  writing_system: 'Schriftsystem',
  language_fact: 'Sprach-Fakt',
  etymology: 'Wortherkunft',
  loanword: 'Lehnwort',
  grammar_fact: 'Grammatik',
  phonetics: 'Phonetik',
  language_curio: 'Sprachkuriosum',
  // Cultura
  artwork: 'Kunstwerk',
  sculpture: 'Skulptur',
  architecture: 'Architektur',
  art_movement: 'Kunstrichtung',
  composer: 'Komponist',
  composition: 'Musikwerk',
  literature: 'Literaturwerk',
  genre_fiction: 'Genre-Literatur',
  literary_movement: 'Literaturepoche',
  // Machina (Digital & Technik)
  programming_language: 'Programmiersprache',
  file_format: 'Dateiformat',
  network_protocol: 'Netzwerkprotokoll',
  data_structure: 'Datenstruktur',
  algorithm: 'Algorithmus',
  hardware: 'Hardware',
  acronym: 'Abkürzung',
  concept: 'Konzept',
  // Machina — klassische Technik (Handwerk/Mechanik/Maschinenbau)
  tool: 'Handwerkzeug',
  machine_element: 'Maschinenelement',
  engine: 'Kraftmaschine',
  manufacturing_process: 'Fertigungsverfahren',
  material: 'Werkstoff',
  simple_machine: 'Einfache Maschine',
  // Historia (Geschichte)
  invention: 'Erfindung',
  discovery: 'Entdeckung',
  epoch: 'Epoche',
  figure: 'Persönlichkeit',
  milestone: 'Meilenstein',
  expedition: 'Expedition',
  // Weitere Astronomie-Kategorien, die nur in Museum/Galerie vorkamen
  // (R3-Zusammenführung der drei zuvor getrennten Label-Tabellen).
  comet: 'Komet',
  meteor_shower: 'Meteorschauer',
  nebula: 'Nebel',
  exoplanet: 'Exoplanet',
  asteroid: 'Asteroid',
  star_cluster: 'Sternhaufen',
  object: 'Objekt',
  // Ältere Galerie-Kategorien
  music: 'Musik',
  quote: 'Zitat',
  script: 'Schrift'
};

// Deutsche Labels fuer haeufige Attribut-Schluessel (Fallback: Roh-Schluessel).
export const ATTR_LABELS = {
  region: 'Region',
  latinName: 'Lateinisch',
  notableFor: 'Bekannt für',
  location: 'Lage',
  system: 'Organsystem',
  // Homo-Attribute der neuen Kategorien (cell_type/hormone/vitamin/sense + Welle 2).
  fachName: 'Fachbegriff',
  gland: 'Bildungsort',
  hormoneClass: 'Hormonklasse',
  chemicalName: 'Chemischer Name',
  solubility: 'Löslichkeit',
  sensoryOrgan: 'Sinnesorgan',
  substrate: 'Substrat',
  domain: 'Bereich',
  foodSource: 'Nahrungsquelle',
  nutrientClass: 'Nährstoffgruppe',
  characteristic: 'Kennzeichen',
  timeframe: 'Zeitspanne',
  kind: 'Art',
  // Homo — Welle 5 (joint/reflex/blood_group).
  jointType: 'Gelenktyp',
  bonesInvolved: 'Beteiligte Knochen',
  movement: 'Beweglichkeit',
  stimulus: 'Reiz (Auslöser)',
  response: 'Reaktion',
  reflexType: 'Reflexart',
  antigen: 'Antigen',
  antibody: 'Antikörper',
  // Der aus dem Verbreitungsgebiet abgeleitete Erdteil hatte als einziges
  // Attribut im ganzen Bestand keine deutsche Bezeichnung und erschien im
  // Konzeptpanel als roher Schluessel „continent" (CodeQA 2026-09-03).
  continent: 'Erdteil',
  // Homo — Welle 6 (Stand 2026-09-02).
  bodyRegion: 'Körperregion',
  vesselType: 'Gefäßart',
  supplies: 'Versorgungsgebiet',
  parentOrgan: 'Sinnesorgan',
  countAdult: 'Anzahl im Gebiss',
  eruptionAgeYears: 'Durchbruch (Jahre)',
  tissueClass: 'Gewebeklasse',
  occurrence: 'Vorkommen',
  componentType: 'Art des Bausteins',
  chemicalClass: 'Stoffklasse',
  producedIn: 'Bildungsort',
  insertion: 'Ansatz',
  nerveKind: 'Nervengruppe',
  cranialNumber: 'Hirnnerv Nr.',
  brainVolumeCc: 'Hirnvolumen (cm³)',
  heightCm: 'Körpergröße (cm)',
  approxWeightGrams: 'Gewicht (g)',
  value: 'Wert',
  unit: 'Einheit',
  epoch: 'Zeitraum',
  type: 'Typ',
  diameterKm: 'Durchmesser (km)',
  distanceAU: 'Entfernung (AE)',
  moons: 'Monde',
  // numMoons/orderFromSun: Text an das bestehende Astra-Panel angeglichen (T1,
  // zuvor abweichende Duplikate in astraBodies.js — dort war 'Monde'/'Position
  // v. Sonne' sichtbar; hier vereinheitlicht, keine andere Domain nutzt die Keys).
  numMoons: 'Monde',
  orbitalPeriod: 'Umlaufzeit',
  orderFromSun: 'Position v. Sonne',
  dayLengthHours: 'Tageslänge (h)',
  yearLengthEarthDays: 'Jahr (Erdtage)',
  surfaceTempC: 'Oberflächentemp. (°C)',
  mass: 'Masse',
  gravity: 'Schwerkraft',
  hostStar: 'Zentralstern',
  constellation: 'Sternbild',
  distanceLy: 'Entfernung (Lj)',
  brightestStar: 'Hellster Stern',
  // Weitere Astra/Homo-Schluessel, damit keine rohen englischen Keys leaken.
  apparentMagnitude: 'Magnitude',
  parentPlanet: 'Zentralplanet',
  yearLengthEarthYears: 'Jahr (Erdjahre)',
  distanceFromSunAU: 'Entfernung (AE)',
  hasRings: 'Ringe',
  discoveredYear: 'Entdeckt',
  definition: 'Definition',
  function: 'Funktion',
  // Natura-Attribute (kanonische Keys aus merge_natura.js).
  class: 'Tierklasse',
  order: 'Ordnung',
  range: 'Verbreitung',
  conservationStatus: 'Schutzstatus (IUCN)',
  maxLengthCm: 'max. Länge (cm)',
  maxWeightKg: 'max. Gewicht (kg)',
  lifespanYears: 'Lebensdauer (Jahre)',
  topSpeedKmh: 'Geschwindigkeit (km/h)',
  maxWingspanCm: 'Spannweite (cm)',
  scientificName: 'Wissenschaftl. Name',
  maxHeightM: 'max. Höhe (m)',
  maxAgeYears: 'max. Alter (Jahre)',
  origin: 'Herkunft',
  mohsHardness: 'Mohshärte',
  kristallsystem: 'Kristallsystem',
  chemischeFormel: 'Chemische Formel',
  lage: 'Lage',
  vulkantyp: 'Vulkantyp',
  // Häufige Natura-Einzelattribute (verhindert rohe camelCase-Keys im Panel).
  herzgewichtKg: 'Herzgewicht (kg)',
  herzfrequenzMin: 'Herzfrequenz (1/min)',
  koerperlaengeCm: 'Körperlänge (cm)',
  maxGewichtG: 'max. Gewicht (g)',
  schulterhoeheMaxCm: 'Schulterhöhe (cm)',
  tiefenbereichM: 'Tiefenbereich (m)',
  maxTauchtiefeM: 'max. Tauchtiefe (m)',
  maxTauchzeitMin: 'max. Tauchzeit (min)',
  beissKraftN: 'Beißkraft (N)',
  maxGroesseMm: 'max. Größe (mm)',
  fluegelschlaegeSekunde: 'Flügelschläge/s',
  migrationsdistanzKm: 'Migrationsdistanz (km)',
  // Lingua (kanonische Keys aus merge_lingua.js)
  speakersMillionsTotal: 'Sprecher gesamt (Mio.)',
  speakersMillionsNative: 'Muttersprachler (Mio.)',
  family: 'Sprachfamilie',
  script: 'Schrift',
  scriptType: 'Schrifttyp',
  countries: 'Länder',
  officialIn: 'Amtssprache in (Ländern)',
  languageCount: 'Anzahl Sprachen',
  mainBranches: 'Hauptzweige',
  distribution: 'Verbreitung',
  shareWorldPopulationPercent: 'Anteil Weltbevölkerung (%)',
  charCount: 'Zeichenanzahl',
  direction: 'Schreibrichtung',
  usersMillions: 'Nutzer (Mio.)',
  languagesUsing: 'Verwendet von',
  sourceLanguage: 'Herkunftssprache',
  originalMeaning: 'Ursprüngliche Bedeutung',
  loanPath: 'Entlehnungsweg',
  loanEra: 'Entlehnungszeit',
  meaning: 'Bedeutung',
  examples: 'Beispiele',
  language: 'Sprache',
  speakersMillions: 'Sprecher (Mio.)',
  inventedYear: 'Erfunden (Jahr)',
  specialFeature: 'Besonderheit',
  firstAttestedYear: 'Erstbeleg (Jahr)',
  caseCount: 'Anzahl Fälle',
  toneCount: 'Anzahl Töne',
  founder: 'Begründer',
  foundedYear: 'Gegründet',
  // Cultura (Keys aus concepts_cultura.json; location/founder/language bereits oben).
  creator: 'Urheber',
  architect: 'Architekt',
  author: 'Autor',
  composer: 'Komponist',
  creationPeriod: 'Entstehungszeit',
  year: 'Jahr',
  yearPart1: 'Jahr (Teil 1)',
  yearPart2: 'Jahr (Teil 2)',
  era: 'Epoche',
  period: 'Periode',
  country: 'Land',
  originCountry: 'Herkunftsland',
  originPlace: 'Herkunftsort',
  originRegion: 'Herkunftsregion',
  nationality: 'Nationalität',
  namesake: 'Namensgeber',
  dedicatee: 'Widmungsträger',
  genre: 'Gattung',
  series: 'Reihe/Zyklus',
  startYear: 'Startjahr',
  style: 'Stil',
  medium: 'Medium',
  material: 'Material',
  musicalKey: 'Tonart',
  keyCenters: 'Tonarten-Zentren',
  movementCount: 'Anzahl Sätze',
  actCount: 'Anzahl Akte',
  cantoCount: 'Anzahl Gesänge',
  concertoCount: 'Anzahl Konzerte',
  operaCount: 'Anzahl Opern',
  partCount: 'Anzahl Teile',
  verseCount: 'Anzahl Verse',
  librettist: 'Librettist',
  finaleLyricist: 'Finale-Textdichter',
  coreIdea: 'Grundidee',
  characteristics: 'Merkmale',
  mainGroups: 'Hauptgruppen',
  mainRepresentatives: 'Hauptvertreter',
  notableExample: 'Bekanntes Beispiel',
  notableWork: 'Bekanntes Werk',
  phases: 'Phasen',
  succeededBy: 'Nachfolger',
  supersedes: 'Vorgänger',
  birthYear: 'Geburtsjahr',
  deathYear: 'Todesjahr',
  lifespan: 'Lebenszeit',
  startYear: 'Startjahr',
  endYear: 'Endjahr',
  unescoYear: 'UNESCO-Jahr',
  heightM: 'Höhe (m)',
  widthM: 'Breite (m)',
  lengthM: 'Länge (m)',
  lengthKm: 'Länge (km)',
  originalHeightM: 'Ursprüngliche Höhe (m)',
  totalHeightWithPedestalM: 'Gesamthöhe mit Sockel (m)',
  elevationM: 'Höhe ü. NN (m)',
  domeHeightM: 'Kuppelhöhe (m)',
  domeDiameterM: 'Kuppeldurchmesser (m)',
  weightT: 'Gewicht (t)',
  capacity: 'Fassungsvermögen',
  interiorArea: 'Innenfläche',
  totalAreaHa: 'Gesamtfläche (ha)',
  durationMin: 'Dauer (min)',
  totalDurationHours: 'Gesamtdauer (h)',
  // Machina (Digital & Technik) — Funktion/Eigenschaft, kein Datum/Person.
  paradigm: 'Paradigma',
  typeSystem: 'Typsystem',
  execution: 'Ausführung',
  primaryDomain: 'Anwendungsbereich',
  fileExtension: 'Dateiendung',
  mediaType: 'Datenart',
  compression: 'Kompression',
  fullName: 'Bedeutung',
  layer: 'Netzwerkschicht',
  defaultPort: 'Standard-Port',
  transport: 'Transportprotokoll',
  purpose: 'Zweck',
  accessComplexity: 'Zugriffskomplexität',
  avgComplexity: 'Zeitkomplexität (Ø)',
  // Machina — klassische Technik
  trade: 'Gewerk',
  energySource: 'Energiequelle',
  principle: 'Wirkprinzip',
  mainGroup: 'Hauptgruppe (DIN 8580)',
  materialClass: 'Werkstoffklasse',
  property: 'Eigenschaft',
  // Historia (Geschichte) — Zeit/Urheberschaft. region/nationality/field s. o.
  inventor: 'Erfinder',
  discoverer: 'Entdecker',
  knownFor: 'Bekannt für',
  protagonist: 'Hauptakteur',
  explorer: 'Entdeckungsreisender',
  precededBy: 'Vorausgehende Epoche',
  field: 'Bereich',
  // Bereichsübergreifende Rohdatenfelder, die in der generischen Konzeptkarte
  // unter den ersten sechs Kennwerten vorkommen. Ohne explizites Label würde
  // React den internen camelCase-Schlüssel unverändert anzeigen.
  category: 'Kategorie',
  authorDeathYear: 'Todesjahr des Urhebers',
  work: 'Werk',
  discoveryMethod: 'Entdeckungsmethode',
  orbitalPeriodDays: 'Umlaufzeit (Tage)',
  launchYear: 'Startjahr',
  operator: 'Betreiber',
  iauAbbreviation: 'IAU-Kürzel',
  visibility: 'Sichtbarkeit',
  launchMassKg: 'Startmasse (kg)',
  radiusEarthRadii: 'Radius (Erdradien)',
  dichte: 'Dichte',
  notableStars: 'Bekannte Sterne',
  completionStem: 'Textanfang',
  completionAnswer: 'Fortsetzung',
  usedAs: 'Verwendung',
  target: 'Ziel',
  essbarkeit: 'Essbarkeit',
  perihelionDistanceAU: 'Periheldistanz (AE)',
  numStars: 'Anzahl Sterne',
  ageMillionYears: 'Alter (Mio. Jahre)',
  orbitalPeriodYears: 'Umlaufzeit (Jahre)',
  messierNumber: 'Messier-Nummer',
  gattung: 'Gattung',
  hauptverbreitungsgebiet: 'Hauptverbreitungsgebiet',
  parentBody: 'Ursprungskörper',
  originApprox: 'Ungefähre Entstehungszeit',
  peakDate: 'Maximum',
  lastPerihelion: 'Letztes Perihel',
  missions: 'Missionen',
  zodiac: 'Tierkreiszeichen',
  typ: 'Typ',
  antagonist: 'Gegenspieler',
  nucleusSizeKm: 'Kerngröße (km)',
  shape: 'Form',
  massJupiterMasses: 'Masse (Jupitermassen)',
  bekanntesterAusbruchJahr: 'Bekanntester Ausbruch',
  hoeheMeter: 'Höhe (m)',
  vorkommen: 'Vorkommen',
  innervates: 'Innerviert',
  originCentury: 'Entstehungsjahrhundert',
  exampleLanguage: 'Beispielsprache',
  example: 'Beispiel',
  erkennungsMerkmal: 'Erkennungsmerkmal',
  diameterLy: 'Durchmesser (Lj)',
  circumpolarCentralEurope: 'Zirkumpolar in Mitteleuropa',
  radiantConstellation: 'Radiant im Sternbild',
  occursIn: 'Vorkommen',
  letzteAktivitaet: 'Letzte Aktivität',
  iauRank: 'IAU-Flächenrang',
  minMassEarthMasses: 'Mindestmasse (Erdmassen)',
  comparison: 'Vergleich',
  exampleGerman: 'Deutsches Beispiel',
  ipaSymbol: 'IPA-Zeichen',
  // Seltene Lingua-Kennwerte aus redaktionellen Einzelkonzepten.
  achievement: 'Leistung',
  activeSpeakers: 'Aktive Sprecher',
  activeUsers: 'Aktive Nutzer',
  adoptedByLanguages: 'Übernommen von Sprachen',
  ageEstimate: 'Geschätztes Alter',
  agreement: 'Kongruenz',
  alphabet: 'Alphabet',
  averageConsonantCount: 'Durchschnittliche Konsonantenzahl',
  bantuLanguageCount: 'Anzahl Bantusprachen',
  bestKnown: 'Bekanntestes Beispiel',
  bestKnownEnglish: 'Bekanntestes englisches Beispiel',
  classCount: 'Anzahl Klassen',
  clickTypeCount: 'Anzahl Klicklauttypen',
  coinedBy: 'Geprägt von',
  coinedYear: 'Prägungsjahr',
  commonlyUsedChars: 'Häufig verwendete Zeichen',
  completeTranslations: 'Vollständige Übersetzungen',
  consonants: 'Konsonanten',
  countInGerman: 'Verbreitung im Deutschen',
  countWorldwide: 'Anzahl weltweit',
  descendants: 'Abgeleitete Schriftsysteme',
  documentedConlangCount: 'Dokumentierte Plansprachen',
  easternmost: 'Östlichster Verbreitungspunkt',
  endangeredSharePercent: 'Gefährdeter Anteil (%)',
  esperantoNativeSpeakers: 'Esperanto-Muttersprachler',
  exampleLatin: 'Lateinisches Beispiel',
  examplePlural: 'Pluralbeispiel',
  exampleWelsh: 'Walisisches Beispiel',
  extinctYear: 'Ausgestorben im Jahr',
  federalState: 'Bundesland',
  fewestSounds: 'Wenigste Laute',
  firstAttestedSource: 'Erste belegte Quelle',
  firstAttestedYearGerman: 'Deutscher Erstbeleg',
  firstUse: 'Erste Verwendung',
  germanGenderCount: 'Genera im Deutschen',
  germanVowelCount: 'Vokale im Deutschen',
  grammar: 'Grammatik',
  grammarType: 'Grammatiktyp',
  guinnessRecord: 'Guinness-Rekord',
  hawaiianPhonemeCount: 'Phoneme im Hawaiischen',
  increasePeriod: 'Vergleichszeitraum',
  languages: 'Sprachen',
  languagesWithGender: 'Sprachen mit Genus',
  languagesWithoutGender: 'Sprachen ohne Genus',
  lastSpeaker: 'Letzter Sprecher',
  letterCount: 'Buchstabenanzahl',
  linguisticExplanation: 'Sprachwissenschaftliche Erklärung',
  literacyRate: 'Alphabetisierungsrate',
  loanEraEnglish: 'Entlehnungszeit im Englischen',
  longestGermanSingleWordPalindrome: 'Längstes deutsches Einwortpalindrom',
  mainFamily: 'Hauptfamilie',
  maxClassCount: 'Höchste Klassenzahl',
  maxMorphemesPerWord: 'Maximale Morpheme pro Wort',
  mostSounds: 'Meiste Laute',
  nativeSharePercent: 'Muttersprachleranteil (%)',
  nativeSpeakers: 'Muttersprachler',
  nativeSpeakersMillions: 'Muttersprachler (Mio.)',
  note: 'Hinweis',
  prefixExample: 'Präfixbeispiel',
  pseudoAnglicisms: 'Scheinanglizismen',
  rankByLanguageCount: 'Rang nach Sprachzahl',
  rankByNativeSpeakers: 'Rang nach Muttersprachlern',
  rankByTotalSpeakers: 'Rang nach Gesamtsprechern',
  recognition: 'Anerkennung',
  reference: 'Referenz',
  scriptInvented: 'Schrift entstanden',
  sourceWord: 'Ausgangswort',
  speakers: 'Sprecher',
  spreadKm: 'Verbreitung (km)',
  spreadMedium: 'Verbreitungsweg',
  statisticsDate: 'Stand der Statistik',
  statisticsSource: 'Statistikquelle',
  strategy: 'Strategie',
  symbolCount: 'Zeichenanzahl',
  technicalTerm: 'Fachbegriff',
  tones: 'Töne',
  top20LanguagesPopulationShare: 'Bevölkerungsanteil der 20 größten Sprachen (%)',
  totalLanguagesWorldwide: 'Sprachen weltweit',
  totalSpeakersMillions: 'Sprecher gesamt (Mio.)',
  types: 'Typen',
  unescoSince: 'UNESCO-Anerkennung seit',
  usage: 'Verwendung',
  usageDuration: 'Nutzungsdauer',
  variantCount: 'Anzahl Varianten',
  vocabularyShare: 'Wortschatzanteil',
  vocabularySharePercent: 'Wortschatzanteil (%)',
  westernmost: 'Westlichster Verbreitungspunkt',
  word: 'Wort',
  wordCount: 'Wortanzahl',
  worldLanguageShare: 'Anteil der Weltsprachen',
  // Seltene Natura-Kennwerte aus redaktionellen Einzelkonzepten.
  absorbiertUV: 'Absorbierte UV-Strahlung',
  aktivitaet: 'Aktivität',
  alterGesteinsMillionenJahre: 'Gesteinsalter (Mio. Jahre)',
  anteilAtmosphaerischesOzonProzent: 'Anteil des atmosphärischen Ozons (%)',
  anteilEisfreierLandflaeche: 'Anteil an der Landfläche',
  anteilErdoberflaecheProzent: 'Anteil der Erdoberfläche (%)',
  anteilGefaehrdeterRiffeIPCC2C: 'Gefährdete Riffe bei 2 °C (%)',
  anteilMeeresflaecheProzent: 'Anteil der Meeresfläche (%)',
  anteilSuessWasserWeltProzent: 'Anteil am weltweiten Süßwasser (%)',
  anzahlHauptplatten: 'Anzahl Hauptplatten',
  artanteilWeltProzent: 'Anteil der weltweiten Arten (%)',
  artenzahl: 'Artenzahl',
  artenzahlBekannt: 'Bekannte Artenzahl',
  atmosphaerenschicht: 'Atmosphärenschicht',
  augendurchmesserCm: 'Augendurchmesser (cm)',
  augenOmmatidia: 'Ommatidien pro Auge',
  ausbruchsdauerSek: 'Ausbruchsdauer (s)',
  ausbruchsintervallMin: 'Ausbruchsintervall (min)',
  begruender: 'Begründer',
  beschleunigung: 'Beschleunigung',
  besonderheit: 'Besonderheit',
  bestaetigt_kmh: 'Bestätigte Geschwindigkeit (km/h)',
  bestaeubtePflanzenArten: 'Bestäubte Nutzpflanzenarten',
  blattanzahl: 'Blattanzahl',
  blitzeWeltProSek: 'Blitze weltweit pro Sekunde',
  blitzlaengeMaxKm: 'Maximale Blitzlänge (km)',
  bluetedauerStunden: 'Blütedauer (h)',
  bluetenDurchmesserCm: 'Blütendurchmesser (cm)',
  bluetenfarbe: 'Blütenfarbe',
  chemischesSymbol: 'Chemisches Symbol',
  datum: 'Datum',
  dauerMs: 'Dauer (ms)',
  dichteDiamantGCm3: 'Dichte von Diamant (g/cm³)',
  dichteGraphitGCm3: 'Dichte von Graphit (g/cm³)',
  dichtGCm3: 'Dichte (g/cm³)',
  dickeAequator_km: 'Dicke am Äquator (km)',
  dickePole_km: 'Dicke an den Polen (km)',
  durchschnittstemperaturC: 'Durchschnittstemperatur (°C)',
  elementSymbol: 'Elementsymbol',
  entstehung: 'Entstehung',
  entstehungstiefKm: 'Entstehungstiefe (km)',
  erstbesteigungJahr: 'Erstbesteigung',
  ersteBlueteJahre: 'Alter bis zur ersten Blüte (Jahre)',
  farbe: 'Farbe',
  farbenReihenfolge: 'Farbreihenfolge',
  flaecheHa: 'Fläche (ha)',
  flaecheMillionenKm2: 'Fläche (Mio. km²)',
  fliessgeschwindigkeitMProJahr: 'Fließgeschwindigkeit (m/Jahr)',
  flugdistanzProTagKm: 'Flugdistanz pro Tag (km)',
  fontaenehoehM: 'Fontänenhöhe (m)',
  fundortUS: 'Fundort',
  gebirge: 'Gebirge',
  gefaehrdungsstatusIUCN: 'IUCN-Gefährdungsstatus',
  genomeGroesseMb: 'Genomgröße (Mb)',
  gesamtflaecheKm2: 'Gesamtfläche (km²)',
  geschaetztesAlterJahre: 'Geschätztes Alter (Jahre)',
  gesicherteMessungTempC: 'Gesicherte Messung (°C)',
  gesichertesDatum: 'Datum der gesicherten Messung',
  giftigsteArt: 'Giftigste Art',
  giftLetaldosis: 'Letaldosis des Gifts',
  globaleMassenbleicheJahre: 'Jahre globaler Massenbleichen',
  groessterGletscherLaengeKm: 'Länge des größten Gletschers (km)',
  groessterGletscherName: 'Größter Gletscher',
  growthCmPerDay: 'Wachstum pro Tag (cm)',
  hartestesMineral: 'Härtestes Mineral',
  hauptgebiete: 'Hauptgebiete',
  hauptprozesse: 'Hauptprozesse',
  hauptursache: 'Hauptursache',
  hauptverbreitung: 'Hauptverbreitung',
  hauptvorkommen: 'Hauptvorkommen',
  hauptwirkstoff: 'Hauptwirkstoff',
  heliotropismusPhase: 'Phase des Heliotropismus',
  hoechsteErhebungM: 'Höchste Erhebung (m)',
  hoeheKm_max: 'Maximale Höhe (km)',
  hoeheKm_min: 'Minimale Höhe (km)',
  hoehenrekordStalagmitM: 'Höhenrekord eines Stalagmiten (m)',
  hoeheUeberNNM: 'Höhe über NN (m)',
  hutDurchmesserCm: 'Hutdurchmesser (cm)',
  industrielleAnwendung: 'Industrielle Anwendung',
  jaehrlicherNiederschlagGlobalMm: 'Globaler Jahresniederschlag (mm)',
  jahreswaechstumMm: 'Jährliches Wachstum (mm)',
  kannibalismus: 'Kannibalismus',
  kavitationstemperaturK: 'Kavitationstemperatur (K)',
  kernRadiusKm: 'Kernradius (km)',
  kernTemperaturC: 'Kerntemperatur (°C)',
  knollengewichtKg: 'Knollengewicht (kg)',
  koerper: 'Körper',
  kohlenstoffspeicherPgC: 'Kohlenstoffspeicher (Pg C)',
  koloniegroesse: 'Koloniegröße',
  kommunikation: 'Kommunikation',
  kontaktwinkelGrad: 'Kontaktwinkel (°)',
  kopfbluetenDurchmesserCm: 'Kopfblütendurchmesser (cm)',
  krusteDickeKm_kontinental: 'Kontinentale Krustendicke (km)',
  krusteDickeKm_ozeanisch: 'Ozeanische Krustendicke (km)',
  krustenhaeufigkeit: 'Häufigkeit in der Erdkruste',
  laender: 'Länder',
  laengeKm: 'Länge (km)',
  letzterAusbruchJahr: 'Letzter Ausbruch',
  luftanteilProzent: 'Anteil der Luftmasse (%)',
  maennchenLaengeCm: 'Länge der Männchen (cm)',
  magnitude: 'Magnitude',
  mantelDickeKm: 'Manteldicke (km)',
  massenanteilErdkrusteProzent: 'Massenanteil der Erdkruste (%)',
  masseTonnen: 'Masse (t)',
  maxAlterJahre: 'Maximales Alter (Jahre)',
  maxBluetenDurchmesserCm: 'Maximaler Blütendurchmesser (cm)',
  maxBluetengewichtKg: 'Maximales Blütengewicht (kg)',
  maxBluetenstandHoeheM: 'Maximale Blütenstandhöhe (m)',
  maxBreiteKm: 'Maximale Breite (km)',
  maxColonySizeMillions: 'Maximale Koloniegröße (Mio.)',
  maxDurchmesserBlattCm: 'Maximaler Blattdurchmesser (cm)',
  maxEigewichtG: 'Maximales Eigewicht (g)',
  maxGesamtlaengeCm: 'Maximale Gesamtlänge (cm)',
  maxHoeheCm: 'Maximale Höhe (cm)',
  maxKoerperlaengeCm: 'Maximale Körperlänge (cm)',
  maxPanzerlaengeCm: 'Maximale Panzerlänge (cm)',
  maxStammumfangM: 'Maximaler Stammumfang (m)',
  maxTidenHubM: 'Maximaler Tidenhub (m)',
  maxTidenHubOrt: 'Ort des maximalen Tidenhubs',
  maxTiefeM: 'Maximale Tiefe (m)',
  maxTiefeName: 'Tiefster Punkt',
  maxTraglastKg: 'Maximale Traglast (kg)',
  maxWassertiefeCm: 'Maximale Wassertiefe (cm)',
  mindestWassertemperaturC: 'Mindestwassertemperatur (°C)',
  mineralstoff: 'Mineralstoff',
  minGewichtG: 'Minimales Gewicht (g)',
  minLengthCm: 'Minimale Länge (cm)',
  mohsHaerteDiamant: 'Mohshärte von Diamant',
  mohsHaerteGraphit: 'Mohshärte von Graphit',
  nationalpark: 'Nationalpark',
  nebenregenbogenWinkelGrad: 'Winkel des Nebenregenbogens (°)',
  nestTiefeMeter: 'Nesttiefe (m)',
  oeffnungswinkelGrad: 'Öffnungswinkel (°)',
  ordnungszahl: 'Ordnungszahl',
  ort: 'Ort',
  parasit: 'Parasitisch',
  permafrostTiefeM: 'Permafrosttiefe (m)',
  plattendickeKm: 'Plattendicke (km)',
  plattengeschwindigkeitCmProJahr_max: 'Maximale Plattengeschwindigkeit (cm/Jahr)',
  plattengeschwindigkeitCmProJahr_min: 'Minimale Plattengeschwindigkeit (cm/Jahr)',
  referenzmineral_mitte: 'Mittleres Referenzmineral',
  rekordspreisEuroKg: 'Rekordpreis (Euro/kg)',
  rekordTempC: 'Temperaturrekord (°C)',
  sandduenenAnteilProzent: 'Sanddünenanteil (%)',
  schichtvulkanBeispiel: 'Beispiel für Schichtvulkane',
  schichtvulkanHangneigungGrad: 'Hangneigung von Schichtvulkanen (°)',
  schildvulkanBeispiel: 'Beispiel für Schildvulkane',
  schildvulkanHangneigungGrad: 'Hangneigung von Schildvulkanen (°)',
  schildvulkanMaxHoeheSeebetM: 'Maximale Schildvulkanhöhe ab Meeresboden (m)',
  schmelzpunktC: 'Schmelzpunkt (°C)',
  schnappdauerMs: 'Schnappdauer (ms)',
  schwarmIndividuenKm2: 'Schwarmdichte (Individuen/km²)',
  schwimmgeschwindigkeitStundeM: 'Schwimmstrecke pro Stunde (m)',
  skala: 'Skala',
  spannungMioVolt: 'Spannung (Mio. Volt)',
  standortHoeheM: 'Standorthöhe (m)',
  stufen: 'Stufen',
  symbiosepartner: 'Symbiosepartner',
  tagesnahrungG: 'Tagesnahrung (g)',
  temperaturabnahmeProKm_C: 'Temperaturabnahme pro km (°C)',
  temperaturBlitzkanal: 'Temperatur im Blitzkanal (°C)',
  temperaturGrenzeUeberschreitungC: 'Temperaturüberschreitung (°C)',
  temperaturToleranzMax: 'Maximale Temperaturtoleranz (°C)',
  temperaturToleranzMin: 'Minimale Temperaturtoleranz (°C)',
  theorieBegrunder: 'Begründer der Theorie',
  tsunamiJa: 'Tsunami',
  ueberwinterungsgebiet: 'Überwinterungsgebiet',
  ursache: 'Ursache',
  verbreitungGrad: 'Verbreitung',
  verdunstungOzeaneProJahrBillionenLiter: 'Ozeanverdunstung pro Jahr (Bio. Liter)',
  verwendung: 'Verwendung',
  volumeM3: 'Volumen (m³)',
  wachstumsrateMmProJahr: 'Wachstumsrate (mm/Jahr)',
  wachstumstiefeCm: 'Wachstumstiefe (cm)',
  wasserdruckBar: 'Wasserdruck (bar)',
  wassertemperaturGrad: 'Wassertemperatur (°C)',
  weibchenLaengeCm: 'Länge der Weibchen (cm)',
  weichstesMineral: 'Weichstes Mineral',
  weltflaecheKm2: 'Weltweite Fläche (km²)',
  wurzeltiefeM: 'Wurzeltiefe (m)',
  zellteilungsdauerMin: 'Zellteilungsdauer (min)',
  zyklusDauer: 'Zyklusdauer',
  // Seltene Astra-Kennwerte aus Missionen, Deep-Sky-Objekten und Phänomenen.
  accuracyMicroArcsec: 'Genauigkeit (Mikrobogensekunden)',
  activityPeriod: 'Aktivitätszeitraum',
  apparentSizeArcmin: 'Scheinbare Größe (Bogenminuten)',
  areaSqDeg: 'Fläche (Quadratgrad)',
  arrokothFlybyYear: 'Arrokoth-Vorbeiflug',
  astronauts: 'Astronauten',
  auroralZoneLatitude: 'Breite der Polarlichtzone (°)',
  budgetBillionUSD: 'Budget (Mrd. US-Dollar)',
  catalog: 'Katalog',
  catalogedObjects: 'Katalogisierte Objekte',
  cause: 'Ursache',
  centralStarTempK: 'Temperatur des Zentralsterns (K)',
  chandrasekharLimitSolarMasses: 'Chandrasekhar-Grenze (Sonnenmassen)',
  collisionProbBy2300Percent: 'Kollisionswahrscheinlichkeit bis 2300 (%)',
  coolingTimeBillionYears: 'Abkühlzeit (Mrd. Jahre)',
  coreCollapseMechanism: 'Kernkollapsmechanismus',
  criticalYear: 'Kritisches Jahr',
  currentDistanceAU: 'Aktuelle Entfernung (AE)',
  densityTonnesPerCm3: 'Dichte (t/cm³)',
  earthApproach2029DistanceKm: 'Erdannäherung 2029 (km)',
  energyReleasedJoule: 'Freigesetzte Energie (J)',
  entrySpeedKmS: 'Eintrittsgeschwindigkeit (km/s)',
  evaHours: 'Außenbordeinsatz (h)',
  eventHorizonDiameterMioKm: 'Ereignishorizont-Durchmesser (Mio. km)',
  exoplanetCandidates: 'Exoplanetenkandidaten',
  firstImageYear: 'Erstes Bild',
  flybyDate: 'Vorbeiflugdatum',
  flybyTargets: 'Vorbeiflugziele',
  frequencyPerLocationYears: 'Häufigkeit je Ort (Jahre)',
  greenAltitudeKm: 'Höhe des grünen Polarlichts (km)',
  heliopauseCrossedYear: 'Heliopause durchquert',
  inclinationDeg: 'Bahnneigung (°)',
  ingenuityMassKg: 'Masse von Ingenuity (kg)',
  interstellarSpaceSince: 'Im interstellaren Raum seit',
  landingDate: 'Landedatum',
  landingSite: 'Landeort',
  lastGalacticVisibleYear: 'Letzte sichtbare galaktische Supernova',
  latinNameNorthernLights: 'Lateinischer Name des Nordlichts',
  launchDate: 'Startdatum',
  longestObservedMin: 'Längste beobachtete Dauer (min)',
  luminositySunMultiple: 'Leuchtkraft (Sonnenleuchtkräfte)',
  magneticFieldTesla: 'Magnetfeld (T)',
  mainColors: 'Hauptfarben',
  mainStars: 'Hauptsterne',
  mainStarsBrighterMag3: 'Sterne heller als Magnitude 3',
  massEarthMasses: 'Masse (Erdmassen)',
  massKg: 'Masse (kg)',
  massM87StarSolarMasses: 'Masse von M87* (Sonnenmassen)',
  massSgrAStarSolarMasses: 'Masse von Sagittarius A* (Sonnenmassen)',
  massSolarMasses: 'Masse (Sonnenmassen)',
  massTonnes: 'Masse (t)',
  maxMassSolarMasses: 'Maximale Masse (Sonnenmassen)',
  maxRotationsPerSecond: 'Maximale Rotationen pro Sekunde',
  maxSizeSolarRadii: 'Maximale Größe (Sonnenradien)',
  maxSpeedKmH: 'Maximale Geschwindigkeit (km/h)',
  maxTotalityMin: 'Maximale Totalität (min)',
  method: 'Methode',
  minSunDistanceMioKm: 'Minimale Sonnenentfernung (Mio. km)',
  minSunDistanceSolarRadii: 'Minimale Sonnenentfernung (Sonnenradien)',
  minTelescopeCm: 'Minimale Teleskopöffnung (cm)',
  mirrorDiameterM: 'Spiegeldurchmesser (m)',
  mirrorSegments: 'Spiegelsegmente',
  missionDurationYears: 'Missionsdauer (Jahre)',
  missionEndDate: 'Missionsende',
  moonAngularDiameterDeg: 'Scheinbarer Monddurchmesser (°)',
  moonLandingDate: 'Mondlandedatum',
  moonStayHours: 'Aufenthalt auf dem Mond (h)',
  nakedEyeVisibleMonths: 'Mit bloßem Auge sichtbar (Monate)',
  nakedEyeVisibleStars: 'Mit bloßem Auge sichtbare Sterne',
  nextMajorSarosCycles: 'Nächste bedeutende Saroszyklen',
  nextPerihelion: 'Nächstes Perihel',
  nextPerihelionYear: 'Nächstes Periheljahr',
  numPlanets: 'Anzahl Planeten',
  observedStars: 'Beobachtete Sterne',
  observers: 'Beobachter',
  onFlagsCount: 'Auf Flaggen dargestellt',
  operationEndYear: 'Betriebsende',
  operationalSinceYear: 'In Betrieb seit',
  orbit: 'Umlaufbahn',
  orbitAltitudeKm: 'Umlaufbahnhöhe (km)',
  orbitAtL2: 'Umlaufbahn um L2',
  parentBodyOrbitalPeriodYears: 'Umlaufzeit des Ursprungskörpers (Jahre)',
  peakDurationHours: 'Dauer des Maximums (h)',
  pillarsHeightLy: 'Höhe der Säulen (Lj)',
  planetsInHabitableZone: 'Planeten in habitabler Zone',
  planetsVisited: 'Besuchte Planeten',
  plutoFlybyDistanceKm: 'Pluto-Vorbeiflugdistanz (km)',
  plutoFlybyYear: 'Pluto-Vorbeiflug',
  position: 'Position',
  progenitorMaxSolarMasses: 'Maximale Vorläufermasse (Sonnenmassen)',
  progenitorMinSolarMasses: 'Minimale Vorläufermasse (Sonnenmassen)',
  pulsarRotationsPerSecond: 'Pulsarrotationen pro Sekunde',
  radiantDeclinationDeg: 'Deklination des Radianten (°)',
  radiantRA: 'Rektaszension des Radianten',
  ratePerMillenniumMilkyWay: 'Rate pro Jahrtausend in der Milchstraße',
  redAltitudeKm: 'Höhe des roten Polarlichts (km)',
  rockSamplesKg: 'Gesteinsproben (kg)',
  rosettaEscortYears: 'Rosetta-Begleitdauer (Jahre)',
  roverMassKg: 'Rovermasse (kg)',
  sampleReturn: 'Probenrückführung',
  saturnArrivalDate: 'Ankunft am Saturn',
  schwarzschildRadiusFormula: 'Schwarzschildradius-Formel',
  searchArea: 'Suchgebiet',
  semiMajorAxisAU: 'Große Halbachse (AE)',
  speedKmH: 'Geschwindigkeit (km/h)',
  starMassSolarMasses: 'Sternmasse (Sonnenmassen)',
  starType: 'Sterntyp',
  stellarTypeMassSolarMasses: 'Masse stellarer Typen (Sonnenmassen)',
  supernovaYear: 'Supernovajahr',
  surfaceTempK: 'Oberflächentemperatur (K)',
  systemAgeBillionYears: 'Systemalter (Mrd. Jahre)',
  typeIaMechanism: 'Mechanismus von Typ Ia',
  typicalDiameterKm: 'Typischer Durchmesser (km)',
  typicalMassSolarMasses: 'Typische Masse (Sonnenmassen)',
  typicalRadiusKm: 'Typischer Radius (km)',
  typicalSizeSolarRadii: 'Typische Größe (Sonnenradien)',
  umbraMaxWidthKm: 'Maximale Breite des Kernschattens (km)',
  wavelengthRange: 'Wellenlängenbereich',
  zhrMax: 'Maximale Zenitrate (ZHR)',
  zhrNormal: 'Normale Zenitrate (ZHR)',
  zhrStormMax: 'Maximale Sturm-Zenitrate (ZHR)',
  // Altbestände mit versehentlich qualifizierten oder abweichenden Schlüsseln.
  characterities: 'Merkmale',
  'attributes.endYear': 'Endjahr',
  'attributes.field': 'Bereich',
  'attributes.category': 'Kategorie',
  'attributes.definition': 'Definition',
  name: 'Name'
};

/**
 * Liefert den sichtbaren Attributnamen. Der Rohschlüssel `family` wird von
 * Pflanzen und Sprachen geteilt; erst die Kategorie entscheidet, welche
 * fachliche Bezeichnung im Panel steht.
 */
export function getAttributeLabel(key, category = '') {
  if (key === 'family' && category === 'plant') return 'Pflanzenfamilie';
  return ATTR_LABELS[key] || key;
}

/** Formatiert gemeinsame primitive Attributwerte für sichtbare deutsche Texte. */
export function formatAttributeValue(value) {
  if (typeof value === 'boolean') return value ? 'ja' : 'nein';
  return String(value);
}

// Diese Freitext-Attribute beschreiben das Konzept so konkret, dass sie vor der
// Antwort oft indirekt die Loesung verraten. Sie werden erst als Erklaerung nach
// der Antwort gezeigt.
// 'knownFor' (Historia-Persönlichkeiten) erst nach der Antwort zeigen: der
// Freitext ("Beiträge zur Quantenmechanik") verriete sonst Feld/Nationalität.
export const POST_ANSWER_ATTRS = new Set(['notableFor', 'definition', 'function', 'knownFor', 'characteristic',
  // Klassische Technik: beschreibende Freitexte, die das Konzept vor der Antwort verraten könnten.
  'principle', 'property',
  // Machina: 'purpose' (Zweck) beschreibt die Funktion so konkret, dass es z.B. bei der
  // Algorithmus-Klassen-Frage die Antwort verrät ("Löst lineare Optimierungsprobleme"
  // → Optimierungsalgorithmus). Die eigenen purpose-Fragen zeigen den Wert als Option,
  // nicht im Panel — daher hier gefahrlos vor der Antwort verbergen. (QA-Fund 2026-07-01)
  'purpose']);

// Taxonomisch korrelierte Attribute: Wird z.B. die ORDNUNG gefragt, verraet die
// sichtbare TIERKLASSE die Antwort oft schon (die Distraktoren sind dann Ordnungen
// anderer Klassen — wer "Vögel" sieht, waehlt die einzige Vogel-Ordnung). Daher vor
// der Antwort das jeweils korrelierte Attribut mit ausblenden (in beide Richtungen).
export const CORRELATED_ATTRS = { order: 'class', class: 'order' };

// Fachlich redundante Geschwister-Attribute: Wird der KEY getestet, verraten die
// aufgefuehrten VALUES die Antwort schon im Panel — die Lebenszeit "1653–1706"
// nennt das Geburtsjahr, der Perioden-String "1905–1913" das Startjahr, die
// Abkuerzungs-Langform (fullName) buchstabiert Bereich/Datenart/Zweck aus, der
// Entlehnungsweg nennt Herkunftssprache und Ursprungsbedeutung. Solche Geschwister
// werden vor der Antwort ZUSAETZLICH zum getesteten Attribut ausgeblendet.
// (QA-Fund 2026-07-01, Panel-Leaks). Wichtig: Es wird nur die SICHTBARE Anzeige
// gefiltert — die Rohdaten bleiben unveraendert, dieselben Attribute sind fuer
// ANDERE Fragen desselben Konzepts weiterhin legitim.
export const LEAKY_SIBLINGS = {
  // Diese Felder enthalten die gesuchte Teilangabe bereits im Klartext.
  scriptType: ['script', 'languagesUsing'],
  launchYear: ['launchDate'],
  gattung: ['scientificName'],
  // Sternlisten nennen den hellsten Stern auch in der generischen Ersatzansicht.
  brightestStar: ['notableStars', 'mainStars'],
  // Personen-Lebensdaten: 'lifespan' nennt Geburts- UND Todesjahr im Klartext.
  birthYear: ['lifespan'],
  deathYear: ['lifespan'],
  // Gegenrichtung: Wird nach den Lebensdaten gefragt, verraten Geburts- und
  // Todesjahr als eigene Chips die Antwort.
  lifespan: ['birthYear', 'deathYear'],
  // Kunstrichtungen/Epochen: Perioden-String und Hauptvertreter datieren die Richtung.
  startYear: ['period', 'mainRepresentatives'],
  endYear: ['period', 'mainRepresentatives'],
  period: ['startYear', 'endYear', 'mainRepresentatives'],
  // Wortherkunft: die vier Etymologie-Attribute verraten sich gegenseitig.
  sourceLanguage: ['loanPath', 'originalMeaning', 'loanEra'],
  originalMeaning: ['loanPath', 'sourceLanguage', 'loanEra'],
  loanPath: ['sourceLanguage', 'originalMeaning', 'loanEra'],
  loanEra: ['loanPath', 'sourceLanguage', 'originalMeaning'],
  // Herkunftsland: Lage ("Galleria Borghese, Rom") bzw. Erfinder verraten das Land.
  country: ['location', 'inventor'],
  // Abkuerzungs-Langform buchstabiert Bereich/Datenart/Zweck aus; die Klammer in
  // avgComplexity ("O(n) (Stromchiffre)") verraet den Zweck.
  domain: ['fullName'],
  mediaType: ['fullName'],
  purpose: ['fullName', 'avgComplexity'],
  // Homo Welle 5: Beweglichkeit ("dreiachsig") verraet den Gelenktyp (Kugelgelenk);
  // Reiz/Reaktion legen die Reflexart nahe; Antigen und Antikoerper sind bei den
  // Blutgruppen komplementaer -> jeweils das Geschwister vor der Antwort ausblenden.
  jointType: ['movement'],
  reflexType: ['stimulus', 'response'],
  antibody: ['antigen'],
  antigen: ['antibody'],
  // Natura: Der Erdteil wird aus dem Verbreitungsgebiet abgeleitet — steht
  // dieses als Chip im Panel, ist die Antwort dort wörtlich abzulesen.
  continent: ['range'],
  // Homo Welle 6: Der lateinische Name buchstabiert Gefaessart und Region aus
  // ("Arteria carotis communis" nennt die Arterie und ueber "carotis" den Hals),
  // das Versorgungsgebiet legt beides ebenfalls nahe. Umgekehrt verraet der
  // lateinische Name die gefragte deutsche Bezeichnung nicht, weil dort das
  // Konzept selbst gesucht ist. Ansatz und Gegenspieler eines Muskels benennen
  // seine Region; die Hirnnerv-Nummer korreliert mit der Nervengruppe.
  bodyRegion: ['location'],
  // Wird nach der Körperregion gefragt, steht die Antwort in mehreren anderen
  // Chips woertlich drin: "Gluteus maximus" hat location "Gesäß / Hüfte",
  // die Funktion nennt "beugt die Hüfte", das Versorgungsgebiet einer Arterie
  // nennt den Arm. Gemessen 2026-09-03: 40 von 63 Muskelregion-Fragen waren so
  // aus dem Panel ablesbar (dazu 10 von 36 Gefaess- und 7 von 29 Nervenfragen).
  region: ['location', 'function', 'notableFor', 'insertion', 'antagonist',
    'supplies', 'innervates', 'nerveKind', 'type'],
  vesselType: ['latinName', 'supplies'],
  supplies: ['latinName'],
  parentOrgan: ['latinName'],
  tissueClass: ['occurrence'],
  occurrence: ['tissueClass'],
  componentType: ['location'],
  chemicalClass: ['producedIn'],
  countAdult: ['eruptionAgeYears'],
  eruptionAgeYears: ['countAdult'],
  nerveKind: ['cranialNumber', 'innervates'],
  cranialNumber: ['nerveKind', 'innervates'],
  insertion: ['antagonist'],
  antagonist: ['insertion'],
  // Wird nach der Funktion eines Muskels gefragt, verrät der sichtbare
  // Gegenspieler sie fast vollständig: Wer als Antagonist den großen
  // Gesäßmuskel (einen Hüftstrecker) liest, weiß, dass der gesuchte Muskel die
  // Hüfte beugt. Der Ansatzknochen grenzt die Funktion ebenfalls stark ein.
  function: ['antagonist', 'insertion'],
  brainVolumeCc: ['heightCm'],
  heightCm: ['brainVolumeCc']
};

/**
 * Selbstverraeter-Guard: Soll das Attribut `key` VOR der Antwort im Panel verborgen
 * werden, wenn `testedAttribute` gefragt ist? Kapselt alle vier Regeln, damit
 * ConceptVisual.jsx (Quiz-Panel) und build_batches.mjs (QA-Harness) exakt dieselbe
 * Logik nutzen und nicht auseinanderdriften.
 */
export function isAttrLeakedBeforeAnswer(key, testedAttribute) {
  if (key === testedAttribute) return true;                    // das gefragte Attribut selbst
  if (CORRELATED_ATTRS[testedAttribute] === key) return true;  // taxonomisch korreliert (order<->class)
  if (POST_ANSWER_ATTRS.has(key)) return true;                 // Freitext-Details generell erst nach Antwort
  const siblings = LEAKY_SIBLINGS[testedAttribute];            // fachlich redundante Geschwister
  return Boolean(siblings && siblings.includes(key));
}

// Diakritika-robuste Normalisierung fuer Text-Vergleiche ("Dvořák" -> "dvorak").
function normalizeForMatch(s) {
  return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

/**
 * Quellen-Selbstverraeter-Guard: Verraet der Quellname `sourceName` den gefragten
 * Wert `testedValue`? Frueher exakte Substring-Pruefung (`includes`) — die scheiterte
 * an Diakritika ("… (Dvořák)" vs. keyed "Antonin Dvorak") und an keyed-Werten, die
 * LAENGER als das Quellfragment sind ("Reinhold Messner und Peter Habeler" vs. Quelle
 * "… Reinhold Messner"). Jetzt diakritika-robust und tokenweise: ein markantes
 * Wort-Token (>=4 Zeichen) des gefragten Werts im Quellnamen genuegt. (QA-Fund 2026-07-01)
 */
export function sourceRevealsValue(sourceName, testedValue) {
  if (testedValue == null) return false;
  const val = normalizeForMatch(testedValue);
  if (val.length < 3) return false;
  const src = normalizeForMatch(sourceName);
  if (src.includes(val)) return true;   // ganzer Wert (kurze Werte, Jahreszahlen)
  const tokens = val.split(/[^a-z0-9]+/).filter(t => t.length >= 4);
  return tokens.some(t => src.includes(t));
}
